language/language/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^wiki/', include('wiki.urls', namespace='wiki')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^.*', include('main.urls')),
]

language/main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
 url(r'^$', views.main, name='main'),
]

language/wiki/urls.py
from django.conf.urls import url
from wiki import views

urlpatterns = [
    url(r'^$', views.wiki, name='wiki'),
    url(r'^about/$', views.about, name='about'),
    url(r'^category/(?P<categoryID>[\w\-]+)/$', views.category, name='category'),
    url(r'^addCategory/$', views.addCategory, name='addCategory'), 
    url(r'^addPage/(?P<categoryID>[\w\-]+)/$', views.addPage, name='addPage'),
    url(r'^deleteCategory/(?P<categoryID>[0-9]+)/$', views.deleteCategory, name='deleteCategory'),
    url(r'^deletePage/(?P<pageID>[0-9]+)/$', views.deletePage, name='deletePage'),
    url(r'^updateCategory/(?P<categoryID>[0-9]+)/$', views.updateCategory, name='updateCategory'),
    url(r'^updatePage/(?P<pageID>[0-9]+)/$', views.updatePage,name='updatePage'),
]

language/wiki/models.py
from django.db import models
from django.template.defaultfilters import slugify

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
   
   
    def save(self, *args, **kwargs):
        self.name = self.name.replace(' ', '-')
        super(Category, self).save(*args, **kwargs)
        
        
    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128, unique=True)
    url = models.URLField()
    views = models.IntegerField(default=0)
    
    
    def save(self, *args, **kwargs):
        self.title = self.title.replace(' ', '-')
        super(Page, self).save(*args, **kwargs)
        
    
    def __str__(self):
        return self.title

language/wiki/forms.py
from django import forms
from wiki.models import Category, Page

 
class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, label='類別名稱', help_text='請輸入類別名稱')
    class Meta:
        model = Category
        fields = ('name', )
class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, label='頁面標題', help_text='請輸入頁面標題')
    url = forms.URLField(max_length=128, label='頁面網址', help_text='請輸入頁面網址')

    class Meta:
        model = Page
        exclude = ('category', 'views')
        
    def clean(self):
        cleanedData = self.cleaned_data
        url = cleanedData.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleanedData['url'] = url
        return cleanedData

language/wiki/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from wiki.models import Category, Page
from wiki.forms import CategoryForm, PageForm
from django.contrib.auth.decorators import login_required


def wiki(request):
    categories = Category.objects.order_by('-likes')
    context = {'categories':categories}
    return render(request, 'wiki/wiki.html', context)


def about(request):
    context = {}
    return render(request, 'wiki/about.html', context)


def category(request, categoryID):
    context = {}
    try:
        category = Category.objects.get(id=int(categoryID))
        context['category'] = category
        context['pages'] = Page.objects.filter(category=category)
    except Category.DoesNotExist:
        pass
    return render(request, 'wiki/category.html', context)
@login_required
def addCategory(request):
    template = 'wiki/addCategory.html'
    if request.method=='GET':
        return render(request, template, {'form':CategoryForm()})
    # request.method=='POST'
    form = CategoryForm(request.POST)
    if not form.is_valid():
        return render(request, template, {'form':form})
    form.save()
    return redirect(reverse('wiki:wiki'))
    # Or try this: return wiki(request) 
@login_required
def addPage(request, categoryID):
    template = 'wiki/addPage.html'
    try:
        pageCategory = Category.objects.get(id=int(categoryID))
    except Category.DoesNotExist:
        return category(request, categoryID)
    context = {'category':pageCategory}
    if request.method=='GET':
        context['form'] = PageForm()
        return render(request, template, context)
    # request.method=='POST'
    form = PageForm(request.POST)
    context['form'] = form
    if not form.is_valid():
        return render(request, template, context)
    page = form.save(commit=False)
    page.category = pageCategory
    page.save()
    return redirect(reverse('wiki:category', args=(categoryID, )))

def deleteCategory(request, categoryID):
    if request.method!='POST':
        return wiki(request)
    # request.method=='POST':
    categoryToDelete = Category.objects.get(id=categoryID)
    if categoryToDelete:
        categoryToDelete.delete()
    return redirect(reverse('wiki:wiki'))

def deletePage(request, pageID):
    if request.method!='POST':
        return wiki(request)
    # request.method=='POST':
    pageToDelete = Page.objects.get(id=pageID)
    if pageToDelete:
        categoryID = pageToDelete.category.id
        pageToDelete.delete()
    else:
        categoryID = ''
    return redirect(reverse('wiki:category', args=(categoryID, )))

@login_required
def updateCategory(request, categoryID):
    template = 'wiki/updateCategory.html'
    try:
        category = Category.objects.get(id=categoryID)
    except Category.DoesNotExist:
        return wiki(request)
    if request.method=='GET':
        form = CategoryForm(instance=category)
        return render(request, template, {'form':form, 'category':category})
    # request.method=='POST'
    form = CategoryForm(request.POST, instance=category)
    if not form.is_valid():
        return render(request, template, {'form':form, 'category':category})
    form.save()
    return redirect(reverse('wiki:wiki'))
                    
@login_required               
def updatePage(request, pageID):
    template = 'wiki/updatePage.html'
    try:
        page = Page.objects.get(id=pageID)
    except Page.DoesNotExist:
        return category(request, '')
    if request.method=='GET':
        form = PageForm(instance=page)
        return render(request, template, {'form':form, 'page':page})
    # request.method=='POST'
    form = PageForm(request.POST, instance=page)
    if not form.is_valid():
        return render(request, template, {'form':form, 'page':page})
    form.save()
    return redirect(reverse('wiki:category', args=(page.category.id,)))
    

language/wiki/templates/wiki/about.html
{% extends "main/base.html" %}
{% load staticfiles %}
{% block heading %}關於{% endblock %}
{% block content %}

{% url 'main:main' as main %}
<br>
<p>我們提供許多程式語言的相關知識，歡迎巡覽.</p>
<br><br>
<a href="{{main}}">回首頁</a>
<p><img src={% static 'main/img/proglang.png' %} alt=程式語言影像></p>
{% endblock %}

language/wiki/templates/wiki/addCategory.html
{% extends "main/base.html" %}
{% block heading %}新增程式語言分類{% endblock %}
{% block content %}
<form method=post action={% url 'wiki:addCategory' %}>
 {% csrf_token %}
 {{form.as_p}}
 <input type=submit value=送出>
</form>
<br>
<p><a href={% url 'wiki:wiki' %}>回 Wiki 頁面</a></p>
{% endblock %}

language/wiki/templates/wiki/addPage.html
{% extends "main/base.html" %}
{% block heading %}新增程式語言分類{% endblock %}
{% block content %}

<form method=post action={% url 'wiki:addPage' category.id %}>
 {% csrf_token %}
 {{form.as_p}}
 <input type=submit value=送出>
</form>
<a href={% url 'wiki:category' category.id %}>到{{category.name}}頁面</a>
{% endblock %}

language/wiki/templates/wiki/category.html
{% extends "main/base.html" %}
{% block heading %}新增程式語言分類{% endblock %}
{% block content %}


{% if category %}

 {% if pages %}
 <table style="text-align: center;" >
 <tr><th>頁面標題</th></tr>
 {% for page in pages %}
 <tr><td><a href={{page.url}}>{{page.title}}</a></td>
 <td>
 {% if user.is_authenticated %}
 <form action={% url 'wiki:updatePage' page.id %}>
 <input type=submit value=修改>
 </form>
 {% endif %}
 </td>
 <td>
 {% if user.is_authenticated %}
 <form method=post action={% url 'wiki:deletePage' page.id %}>
 {% csrf_token %}
 <input type=submit value=刪除>
 </form>
 {% endif %}
 </td> 
 </tr>
 
 {% endfor %}
 </table>
 {% else %}
 <p><strong>此類別目前並無頁面。</strong></p>
 {% endif %}
 {% if user.is_authenticated %}
 <p><a href={% url 'wiki:addPage' category.id %}>新增頁面</a></p>
 {% endif %} 
{% else %}
 <p>所指定的類別「{{categoryID}}」不存在。</p>
{% endif %}
{% endblock %}

language/wiki/templates/wiki/updateCategory.html
{% extends "main/base.html" %}
{% block heading %}修改「{{category.name}}」{% endblock %}
{% block content %}

<form method=post action={% url 'wiki:updateCategory' category.id %}>
 {% csrf_token %}
 {{form.as_p}}
 <input type=submit value=送出>
</form>
<br>
<p><a href={% url 'wiki:wiki' %}>回 Wiki 網頁</a></p>
{% endblock %}

language/wiki/templates/wiki/updatePage.html
{% extends "main/base.html" %}
{% block heading %}修改「{{category.name}}」{% endblock %}
{% block content %}

<form method=post action={% url 'wiki:updatePage' page.id %}>
 {% csrf_token %}
 {{form.as_p}}
 <input type=submit value=送出>
</form>
<br>
<p><a href={% url 'wiki:category' page.category.id %}>回「{{page.category.name}}」網頁
</a></p>
{% endblock %}

language/wiki/templates/wiki/wiki.html
{% extends "main/base.html" %}
{% block heading %}程式語言分類{% endblock %}
{% block content %}

{% if categories %}
 <h2>程式語言類別：</h2>
 <table>
 <tr><th>分類名稱</th><th></th>><th></th></tr>
 {% for category in categories %}
 <tr>
 <td>
 <a href={% url 'wiki:category' category.id %}>{{category.name}}</a>
 </td>
 <td>
 {% if user.is_authenticated %}
 <form action={% url 'wiki:updateCategory' category.id %}>
 <input type="submit" value=修改>
 </form>
 {% endif %}
 </td>
 <td>
 {% if user.is_authenticated %} 
 <form method=post action={% url 'wiki:deleteCategory' category.id %}>
 {% csrf_token %}
 <input type=submit value=刪除>
 </form>
 {% endif %}
 </td>
 </tr>
 {% endfor %}
 </table>
 {% else %}
 <p><strong>目前尚未設定程式語言類別。</strong></p>
{% endif %}

{% url 'main:main' as main %}
{% if user.is_authenticated %}
<p><a href={% url 'wiki:addCategory' %}>新增程式語言分類</a></p>
<a href="{{main}}">回首頁</a>
{% endif %}
<br>
{% endblock %}