language/account/urls.py
from django.conf.urls import url
from account import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^userLogin/$', views.userLogin, name='userLogin'),
    url(r'^userLogout/$', views.userLogout, name='userLogout'),
]

language/language/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^wiki/', include('wiki.urls', namespace='wiki')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^.*', include('main.urls')),
]

language/main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
 url(r'^$', views.main, name='main'),
]

language/wiki/urls.py
from django.conf.urls import url
from wiki import views

urlpatterns = [
    url(r'^$', views.wiki, name='wiki'),
    url(r'^about/$', views.about, name='about'),
    url(r'^category/(?P<categoryID>[\w\-]+)/$', views.category, name='category'),
    url(r'^addCategory/$', views.addCategory, name='addCategory'), 
    url(r'^addPage/(?P<categoryID>[\w\-]+)/$', views.addPage, name='addPage'),
    url(r'^deleteCategory/(?P<categoryID>[0-9]+)/$', views.deleteCategory, name='deleteCategory'),
    url(r'^deletePage/(?P<pageID>[0-9]+)/$', views.deletePage, name='deletePage'),
    url(r'^updateCategory/(?P<categoryID>[0-9]+)/$', views.updateCategory, name='updateCategory'),
    url(r'^updatePage/(?P<pageID>[0-9]+)/$', views.updatePage,name='updatePage'),
]

language/main/models.py
from django.db import models

# Create your models here.

language/main/views.py
from django.shortcuts import render
import datetime

def main(request):
    context = {'message':'Django 很棒',"time":datetime.datetime.strftime(datetime.datetime.now(), '%Y-%m-%d %H:%M:%S')}
    return render(request, 'main/main.html', context)

language/main/templates/main/base.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>程式語言小百科</title>
<meta charset=utf-8>
<link rel=stylesheet href={% static 'main/css/main.css' %}>
</head>
<body>
<h1 align="center">普司伊 電視遊樂器專賣店</h1> {% block heading %}{% endblock %}</h1>
{% block content %}{% endblock %}
</body>
</html>

language/main/templates/main/main.html
{% extends "main/base.html" %}
{% block heading %}首頁{% endblock %}
{% block content %}
<p>{{like}}</p>
{% if messages %}
 {% for message in messages %}
 <p {% if message.tags %} class={{message.tags}} {% endif %}>{{message}}</p>
 {% endfor %}
{% endif %}
{% if user.is_authenticated %}
<p><a href={% url 'wiki:about' %}>關於</a></p>
<p><a href={% url 'wiki:wiki' %}>商品總攬</a></p>
 <p><a href={% url 'account:userLogout' %}>登出 ({{user.username}})</a></p>
{% else %}
<p align="right" valign="top" class="main-log"><a href={% url 'account:register' %}>註冊</a>&nbsp;&nbsp;<a href={% url 'account:userLogin' %}>登入</a></p>
<p><a href={% url 'wiki:about' %}>關於</a></p>
<p><a href={% url 'wiki:wiki' %}>商品總攬</a></p>


<br>
{% endif %}


{% endblock %}